### ISSUE TITLE
Help Sending App Data To TenStreet

### ISSUE THREAD

**Issue by jmikeguchi** [zaus/forms-3rdparty-xpost#16]
I am trying to connect a contact form 7 form on page: http://circledelivers.com/owner-operators/ with TenStreet (a company handling application request for this company). I have downloaded your plugin to help me send the form data to TenStreet but I am not familiar with the coding lingo and becoming quite confused by reading over their document and how I am to integrate their information into the fields required with your plugin. Here is their documentation page for what I am to do: https://resources.tenstreet.com/api/docs/Sending_Application_Data_to_Tenstreet.pdf

I have tried to work with TenStreet but they will not help with any technical exchanges. If possible, could you check out the document from TenStreet and point me in the right direction. If you could handle this altogether for me how much would it cost based on the information provided by the document?

**Comment by zaus** [comment]
Wow they sound awfully pompous.  But it looks like a straightforward XML (WSDL) integration with a couple caveats:
1. Needs a unique identifier -- easily accomplished with my "Forms 3rdparty Dynamic Fields" plugin
2. They "require" that you keep logs of both the request and response for > *1 year* for auditing purposes.  To do this you could leave debug mode on, which would give you a copy of both as an email.  If you want to save them to a file that would be a bit of extra work.  I'd also mention compliance (e.g. PCI or whatever's relevant) to keeping full records of PII (personally-identifiable information) in email or on your server.
3. Multiple child nodes (Licenses, Employers) -- just make sure you use the new `[%]` separator behavior if you're sending more than one; otherwise a simple nested mapping will do.
4. You can check for the "success clause" of `Accepted`, but if you want to display specific detail about why it wasn't accepted you'd need to parse the response.

So, nothing difficult.  You can nest sub-fields by mapping to `Authentication/ClientId` or `PersonalData/GovernmentID/@issuingAuthority` etc, as described by the FAQ of this plugin.  Probably the hardest part is setting up the contact form itself just because it can have so many fields.

If you're interested in a quote please contact me through my website.

**Comment by zaus** [comment]
And some example mappings to get you started

```
FORM                API                                                                       IsVal?
first-name          PersonalData/PersonName/GivenName
last-name          PersonalData/PersonName/FamilyName
my-ref-string      ApplicationData/AppReferer                                 Yes
```

**Comment by jmikeguchi** [comment]
I agree, but I guess this is what I have to deal with. I'll take your
information and see how far I can get with them. If I'm unsuccessful I'll
contact you. I really appreciate your response. Thank you ver much!

Joey

**Comment by jmikeguchi** [comment]
Hi Zaus,

I replied through your website about how much it would cost for you to help me set up this API with tenstreet but have not heard from you. Just sending you an email theough here to see if this contact might be better.

Thanks,
Joey Ikeguchi
