### ISSUE TITLE
Need help with hmac header authentication

### ISSUE THREAD

**Issue by Carlitos-Wayoff** [zaus/forms-3rdparty-xpost#25]
Can this be done with this plugin?? http://developer.urb-it.com/docs/create-the-hmac-signature/
One comment on this page is the json body must be in javascript, that is not necessary here.

**Comment by zaus** [comment]
Not intrinsically, but you can [hook to the same 'service_filter_args'](https://github.com/zaus/forms-3rdparty-xpost/blob/master/forms-3rdparty-xpost.php#L33) that this plugin does (with a lower priority value to get there before this plugin transforms the body, if necessary) to add your own processing.

It does support shortcodes in the header so you could write one instead, but since you need access to the submission it's probably not that useful.
